graph LR;

Ap1[2/1 region AE] --> Bp1[2/2]
Bp1 --> Cp1[2/3]
Cp1 --> Dp1[2/4]

Ap2[2/1 region BD] --> Bp2[2/2]
Bp2 --> Cp2[2/3]
Cp2 --> Dp2[2/4]

Ap3[2/1 region CF] --> Bp3[2/2]
Bp3 --> Cp3[2/3]
Cp3 --> Dp3[2/4]
