graph LR;
k1(Kafka Partition 1);
k2(Kafka Partition 2);
conv1(RowToColumn 1);
conv2(RowToColumn 2);
c1(Cassandra);
k1-- Rows 1,2,3 -->conv1;
k2-- Rows 1,2,3 -->conv2;
conv1-- Columnar Chunks -->c1;
conv2-- Columnar Chunks -->c1;
c1 -->s1(Spark RDD Part 1);
c1 -->s2(Spark RDD Part 2);

