graph LR;
E1(IoT data);
E2(Event data);
k1(Kafka);
c1(Cassandra);
E1-- Events 1,2,3 -->k1;
E2-- Events 1,2,3 -->k1;
k1 --> S(Spark Streaming);
S --> F(FiloDB);
F-- Columnar Chunks -->c1;
c1 -->s1(Spark RDD Part 1);
c1 -->s2(Spark RDD Part 2);

