graph LR;
K(Kafka);
C(Cassandra);
SS(Spark Streaming);
F(FiloDB);
StreetSweeperData --> K;
311Data --> K;
911Data --> K;
K-- Rows 1,2,3 -->SS;
SS --> F;
F --> C;
C -->S(Spark SQL);
F --> SS;
SS --> RTA[RealTimeAlerts];

