graph TB
  P[Polygon] --> LR[LinearRing shell]
  P --> LRH1[LinearRing hole1]
  LR --> CS1[CoordinateSequence]
  LRH1 --> CS2[CoordinateSequence 2]
  CS1 --> C1[Coord 1]
  CS1 --> C2[Coord 2]
  CS1 --> C3[Coord 3]
  CS1 --> C4[Coord 4]